##------------------------------------------------------ 站点配置 -----------------------------------------------------##
# baseurl:
# 在服务器上建站时，如果你不需要子域名，请将这一格留空
# 如果你在使用 GitHub Pages, 请将 baseurl 设置为你的网址的子域名
# 例如，当你的域名是 "kaeyleo.github.io"  时，这个 url 需要留空
# 但是，如果你创建了一个叫 "myblog" 的网站，此时网址会变成 "kaeyleo.github.io/myblog" ，这时再将 baseurl 设置为 '/myblog'

title: 'Memo.z'
description: '备忘录'
keyword: 'memorandum'
url: 'shane21.com' # your host
baseurl: ''
favicon: "/assets/image/favicon/favicon.ico"

##------------------------------------------------------ 个人信息 -----------------------------------------------------##
author: 'shane.z'
nickname: 'shane.z'
bio: '备忘录'
avatar: '/assets/image/avadar/1.jfif'
sns:
  show: false
  github: 'https://github.com/shane-zfx'
  email: 'zffxxx7@gmail.com'
  weibo: 'https://weibo.com/username'

##------------------------------------------------------ 功能信息 -----------------------------------------------------##
theme-color: default                                                      # 站点主题色，默认（蓝色，default）和粉色（pink）
postPatterns: 'food'                                                      # 文章封面默认模式，仅在未定义封面图时生效。支持 circuitBoard，overlappingCircles，food，glamorous，ticTacToe，seaOfClouds 五种
nightMode: false                                                          # 夜间模式是否默认开启
tos: ''                                                                   # 站点服务条款链接
permalink: /:categories/:title                                            # 文章页自动生成规则
mathjax: true                                                             # 是否开启 MathJax 公式支持
RSS: true                                                                 # 是否开启 RSS 生成，robots.txt 和 sitemap.xml 文件。
timezone: Asia/Shanghai                                                   # 默认时区
formats:
  time: 0                                                                 # 时间格式，0 -- 2022-04-29  1 -- 29 Apr 2022  2 -- 2022年4月29日

nav:                                                                      # 顶部导航栏，键值对定义显示名称与链接，可以是中文名（需使用引号）
  home: '/'
  blog: '/blog/index.html'
  archives: '/archives'
  tags: '/tags'
  about: '/about'

links:                                                                    # 侧边栏配置，友情链接（侧边栏），键值对定义显示名称与链接，可以是中文名（需使用引号）。
calendar: true                                                            # 是否开启文章发表日历（侧边栏与归档页）
recommend-tags: true                                                      # 是否显示推荐便签
recommend-condition-size: 12                                              # 显示推荐标签数量

pagination:
  enabled: true
  per_page: 5
  permalink: 'page:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

footer:                                                                   # 底部版权栏
  since: 2024                                                             # 站点建站年份，用于显示版权起始时间。
alivetime: true                                                           # 是否开启实时计算站点存活时间（底部）
alivestart: "11/08/2024"                                                  # 站点建站年月日，用于实时计算站点存活时间。
supports:                                                                 # 赞助商徽章
  upyun: false
  webify: false
badges:                                                                   # 其他徽章
  foreverblog: false
  wormhole: false
  travelling: false
  notbyAI: true
cclicense: true                                                           # 是否以 Creative Commons 协议共享文章内容版权
beian: ''                                                                 # ICP 备案信息

languages: [ 'zh-Hans', 'zh-Hant', 'en', 'ja' ]                           # 国际化语言支持列表
default_lang: 'zh-Hans'                                                   # 默认语言

github:                                                                   # 文章最近更新时间自动更新
  enabled: true                                                           # 是否开启
  owner: shane-zfx
  repository: shane-zfx.github.io                                         # 项目名

toc: true                                                                 # 是否开启文章页目录导航
social-share: true                                                        # 是否开启社交分享
social-share-items:                                                       # 社交分享列表
  - wechat
  - twitter
  - facebook
  - linkedin

markdown: kramdown                                                        # Markdown 语法解析器
kramdown:                                                                 # Markdown 语法解析器配置
  input: GFM
highlighter: rouge                                                        # 代码高亮解析器
prism:                                                                    # 代码高亮主题配置节
  theme: one-light                                                        # 代码高亮主题，支持所有官方主题
  line_numbers: true                                                      # 是否开启代码行号
mermaid: true                                                             # 是否开启代码流程图支持，可以根据符合 mermaid 语法的代码画图

extlinks:                                                                 # 区分站内链接与站外链接
  attributes: { rel: nofollow, target: _blank, class: extlinks }          # 站外链接配置
  rel_exclude: [ 'host1.com', 'host2.net' ]                               # 可以被认为是站内链接的多域名配置

premonition:                                                              # 支持五种提示框，note、info、warning、error、citation。
  default:                                                                # 一般采用默认配置即可，无须自定义修改。
    template: '<div class="premonition {{type}}">
          <div class="header">
            <svg class="icon {{type}}" aria-hidden="true">
                <use xlink:href="#icon-{{type}}"></use>
            </svg>
            <div class="title"> {{title}} </div>
          </div>
          <div class="content">
            {{content}}
          </div>
        </div>'
  types:
    citation:
      template: '<div class="premonition {{type}}">
          <div class="header">
            <svg class="icon {{type}}" aria-hidden="true">
                <use xlink:href="#icon-{{type}}"></use>
            </svg>     
          </div>
          <div class="content">
            {{content}}
          </div>
          {% if title %}<div class="ref"> ------ {{title}} </div>{% endif %}
        </div>'
      default_title: ''
    note:
      default_title: 'Note'
    info:
      default_title: 'Info'
    warning:
      default_title: 'Warning'
    error:
      default_title: 'Error'
plugins: [ jekyll-paginate-v2, jekyll-feed, jekyll-sitemap, premonition, h2o-ac-jekyll-extlinks ]
exclude: [ 'node_modules', 'dev', 'package.json', 'webpack.config.js', '.gitignore', 'README.md', '*.gemspec', '*.gem' ]


webpusher:                                                                # 动态消息、通知推送，定义时自动开启。

pwa:
  color: '#ffffff'                                                        # 主题色，默认#81BBFF
  short_name: 'Memo'                                                      # 应用缩写或应用名
  icon192: "/assets/image/web-app-manifest-192x192.png"
  icon512: "/assets/image/web-app-manifest-512x512.png"
  icon_maskable_192: "/assets/image/web-app-manifest-192x192.png"
  icon_maskable_512: "/assets/image/web-app-manifest-512x512.png"
  appleicon: "/assets/image/apple-touch-icon.png"
search: true                                                              # 是否启用搜索
search_type: docsearch                                                    # 默认为 default 即简单搜索，自 v1.3.2 后可用 DocSearch 搜索。
docsearch:                                                                # DocSearch 搜索配置节
  appId: 'AH3DA24C7J'                                                     # 获取的应用 ID
  apiKey: '67e5ce7e7b2f07af1a473906ddf115a5'                              # 获取的应用 Key
  indexName: 'shane.z'                                                    # 获取的索引空间名


comments:                                                                 # 评论功能
  disqus: true                                                            # 是否开启 Disqus 评论
  disqus_url: 'https://shane.disqus.com/embed.js'                         # Disqus 链接
  waline: false                                                           # 是否开启 Waline 评论
  waline_url: ''                           # Waline 链接
  waline_reaction: true                                                   # 是否开启 Waline 表情反馈，以下为自定义本地化配置。
  waline_locale: "{reaction0: '赞一个', reaction1: '踩一下', reaction2: '有点酷', reaction3: '看不懂', reaction4: '啥玩意', reaction5: '想睡觉'}"

#cnzz: '111111111'                                                         # 站点统计功能 CNZZ 站长统计
busuanzi: true                                                            # Busuanzi 不蒜子统计
google_analytics: 'G-MCY34DN0V1'                                          # 谷歌统计分析
google_search: '1XucGFBtekJCV'                                            # 谷歌搜索验证所有权
umami:                                                                    # Umami 统计
  status: false
  id: '{Umami ID}'
  js: 'https://umami.jekyll-theme-h2o-ac.com/umami.js'